In [3]:
import numpy as np

hi

In [4]:
b=np.array(5)
b

array(5)

In [5]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
b=b.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
print(b.shape)
print(b.dtype)
print(b.size)
print(b.ndim)

(3, 5)
int64
15
2


In [13]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
a=np.array([1,2,3,4])
c=np.arange(4)

In [15]:
a*c

array([ 0,  2,  6, 12])

In [16]:
a=a.reshape(4,1)
a

array([[1],
       [2],
       [3],
       [4]])

In [22]:
c@a

array([20])